from typing import List, Any, Type

def array(array:List, fmt:str) -> object: ...
def toList(pointer:object, length:int, fmt:str) -> List: ...
def get_by_index(pointer:object, index:int, fmt:str) -> object: ...
def get_by_slice(pointer:object, length:int, start:int, stop:int, step:int, fmt:str) -> object: ...
def set_by_index(pointer:object, length:int, index:int, fmt:str, value:Any) -> None: ...
def set_by_slice(pointer:object, length:int, start:int, stop:int, step:int, fmt:str, value:List) -> None: ...
