from typing import List, Union, Any

# these functions are defined at 'pynum/csrc/pycu.cu'
def toCuda(capsule:object, length:int, fmt:str) -> object: ...
def toHost(capsule:object, length:int, fmt:str) -> object: ...
def get_by_index(capsule:object, length:int, fmt:str) -> object: ...
def get_by_slice(capsule:object, length:int, start:int, stop:int, step:int, fmt:str) -> object: ...
def set_by_index(capsule:object, length:int, index:int, fmt:str, value:Any) -> None: ...
def set_by_slice(capsule:object, length:int, start:int, stop:int, step:int, fmt:str, value:List) -> None: ...
