# all the functions are defined at `./pycu.cu`

from typing import Any, List

def toCuda(pointer:Any, length:int, fmt:str) -> List[Any]: ...
def toHost(pointer:Any, length:int, fmt:str) -> List[Any]: ...
def getitem_index(pointer:Any, index:int, fmt:str) -> List[Any]: ...
def getitem_slice(pointer:Any, start:int, stop:int, step:int, fmt:str) -> List[Any]: ...
def setitem_index(pointer:Any, value:Any, length:int, index:int, fmt:str) -> None: ...
def setitem_slice(pointer:Any, values:Any, length:int, start:int, stop:int, step:int, fmt:str) -> None: ...
