from typing import List, Union

def toCuda(capsule:object, length:int, fmt:str) -> object: ...
def toHost(capsule:object, length:int, fmt:str) -> object: ...
def get(capsule:object, length:int, fmt:str) -> object: ...